#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser()
group_action = parser.add_mutually_exclusive_group()
group_action.add_argument("-c", "--create", action="store_true",
                          help="create archive")
group_action.add_argument("-x", "-extract", action="store_true",
                          help="extract archive")
group_action.add_argument("-t", "--list", action="store_true",
                          help="list contents of archive")
parser.add_argument("-v", "--verbose", action="count", default=0,
                    help="increase output verbosity")
parser.add_argument("-f", "--file",
                    help="name file of the archive")
parser.add_argument("--host",
                    help="URL of S3 gateway to connect to")
parser.add_argument("--access_key",
                    help="access key")
parser.add_argument("--secret_key",
                    help="secret key")
parser.add_argument("-T", "--files-from",
                    help="list of files to process")
parser.add_argument("--null", action="store_true",
                    help="list of files is null terminated, goot for find --print0")
parser.add_argument("bucket",
                    help="S3 bucket to process")
args = parser.parse_args()
verbosity=args.verbose
print(args.verbose)
print(args.access_key)
print(args.secret_key)
print(args.host)
print(args.files_from)
print(args.file)
print(args.bucket)
